### ISSUE TITLE
Auto-add rows/columns when pasting into the editor

### ISSUE THREAD

**Issue by dericke** [sswatson/table-editor-vscode#6]
Just discovered this extension and I think it's going to be very useful in my work. Thank you for publishing it!

I noticed that, when pasting data into a new Table Editor, the data will get truncated if it's bigger than the default 4x4 table. It would be great if the table could automatically grow to fit the data being pasted into it.

Why this would be helpful: I've found that pasting into a new table works better than pasting into a new document and then creating a table in the specific circumstance that the source table wasn't copied in full. For example, while trying to extract the first column from a table, I didn't bother to select all the cells of the last row, and the "Open CSV in Table Editor" command failed to import it. Opening a blank Table Editor and pasting into that worked, but only after I created enough rows and columns to fit the data.

**Comment by sswatson** [comment]
Actually, it looks like I was mis-remembering which project I created that feature in. It's missing here -- I'll add it now.

Also, due to the way the underlying library is constructed, it's quite tricky to override the default paste behavior. So I'm going to leave "Expand and Paste" as a menu option for now.

**Comment by sswatson** [comment]
This is available now in `v0.3.15` on the Extension Marketplace.
